### ISSUE TITLE
Blank Nodes (Blender 2.93)

### ISSUE THREAD

**Issue by gaemerTsweat** [MaximeHerpin/modular_tree#277] opened 2021-06-18 06:29 UTC
![image](https://user-images.githubusercontent.com/86095760/122516191-0af1c300-d041-11eb-8bf1-4b8124ac6fc1.png)

![image](https://user-images.githubusercontent.com/86095760/122516148-f9a8b680-d040-11eb-87c7-2622df5849c9.png)

![image](https://user-images.githubusercontent.com/86095760/122516627-9408fa00-d041-11eb-9349-34cbaa429027.png)

**Comment by TheGremanCharizard** [comment] 2021-06-21 20:46
Oh yes I have the same Problem.
I can confirm that Bug. 
![Blender 20 06 2021 20_28_49](https://user-images.githubusercontent.com/86265925/122825652-83c37a00-d2e2-11eb-826b-d98f63db26e5.png)

**Comment by Adridri24** [comment] 2021-07-05 16:59
The solution can be found in #281

Errors are due to changes on the Blender Python API side, try this fix:
https://blenderartists.org/uploads/short-url/jJdvhznoccp0VVqHMgzi3nfoYhe.zip

**Comment by wayabove** [comment] 2021-08-03 07:40
> The solution can be found in #281
> 
> Errors are due to changes on the Blender Python API side, try this fix:
> https://blenderartists.org/uploads/short-url/jJdvhznoccp0VVqHMgzi3nfoYhe.zip

Thanks for the fixes!

**Comment by MaximeHerpin** [comment] 2021-12-11 02:59
Fixed in latest version.

**Closed by MaximeHerpin** 2021-12-11 02:59 UTC
